[tools]
betterleaks = "latest"
actionlint = "latest"
shellcheck = "latest"
zizmor = "latest"
hk = "latest"
pkl = "latest"
tombi = "latest"

[tasks.install]
description = "Install tools, hook up hooks, and prepare environment"
run = """
hk install --mise
"""

[tasks.hk]
description = "Run checks on all files"
run = """
hk check --all
"""
