[tools]
gitleaks = "8.30.1"
hk = "2.0.1"
actionlint = "latest"
shellcheck = "latest"
zizmor = "latest"

[tasks.install]
description = "Install tools, hook up hooks, and prepare environment"
run = """
hk install --mise
"""

[tasks.hk]
description = "Run checks on all files"
run = """
hk check --all
"""
